More metrics
vostok/airlock.gate pull request #6
Opened 2017-10-06 13:37 UTC by trurl123

2017-10-07 17:04 UTC, beevee requested changes

2017-10-07 17:04 UTC, beevee commented on src/main/java/ru/kontur/airlock/HttpServer.java
> +                getErrorMeter("apikey").mark();
Тут хорошо бы уточнить: `apikey-missing`, потому что при неправильном апиключе будет другой код ответа.

2017-10-07 17:04 UTC, beevee commented on src/main/java/ru/kontur/airlock/HttpServer.java
> +                getErrorMeter("emptybody").mark();
(это чисто вкусовщина) Если примешь предыдущее замечание про `apikey-missing`, то здесь я бы тоже разделил слова: `empty-body`.

2017-10-07 17:04 UTC, beevee commented on src/main/java/ru/kontur/airlock/HttpServer.java
> +        Log.warn(message);
Кажется, тут не хватит информации в логе для разбирательств. Нужно добавить, по какому apikey произошла ошибка.

2017-10-07 17:04 UTC, beevee commented on src/main/java/ru/kontur/airlock/HttpServer.java
Кажется, пропустил метрику по ошибке 400, когда все эвент группы отфильтровались валидатором (двумя строками ниже, я почему-то не могу туда комментарий добавить.

2017-10-07 17:04 UTC, beevee commented on src/main/java/ru/kontur/airlock/HttpServer.java
...ну и по коду 203 надо тоже метрику среди ошибок нарисовать. Потому что часть сообщений мы приняли, но все равно надо разбираться, почему часть сообщений битые.

2017-10-09 04:55 UTC, trurl123 commented on src/main/java/ru/kontur/airlock/HttpServer.java
Оба эти случая покрываются случаем, когда невалидный routingkey. Ну ок, если нужно, то сделаю и такие метрики.

2017-10-09 07:17 UTC, merged